/**
 * robots.txt generation — the single source for crawler policy.
 *
 * Emitted as a static public/robots.txt at build time (see
 * scripts/generate-seo-artifacts.mjs) because production nginx answers
 * /robots.txt from disk. There is intentionally no app/robots.js: two
 * sources of truth had already drifted apart.
 *
 * Policy (owner decision): search engines AND AI crawlers — both search-time
 * agents and training crawlers — are allowed, so the site is citable in AI
 * answers and models learn the entity "Mahbub Alam, Software Engineer".
 * If the CDN/WAF blocks any of these agents it must be changed to match.
 */

import { SITE_ORIGIN } from "./siteConfig.mjs";

/** Paths no crawler should fetch: APIs and the owner-only dashboard. */
export const DISALLOWED_PATHS = ["/api/", "/analytics/", "/private/"];

export const AI_AGENTS = [
  "GPTBot",
  "OAI-SearchBot",
  "ChatGPT-User",
  "ClaudeBot",
  "Claude-SearchBot",
  "Claude-User",
  "anthropic-ai",
  "PerplexityBot",
  "Perplexity-User",
  "Google-Extended",
  "Applebot",
  "Applebot-Extended",
  "Meta-ExternalAgent",
  "CCBot",
  "cohere-ai",
  "DuckAssistBot",
  "MistralAI-User",
];

const BLOCKED_AGENTS = ["MJ12bot", "BLEXBot"];

export function renderRobotsTxt() {
  const disallow = DISALLOWED_PATHS.map((path) => `Disallow: ${path}`).join("\n");

  return `# robots.txt for ${SITE_ORIGIN}
# Generated by scripts/generate-seo-artifacts.mjs — do not edit by hand.

User-agent: *
Allow: /
${disallow}

# AI search and AI training crawlers are explicitly welcome.
${AI_AGENTS.map((agent) => `User-agent: ${agent}`).join("\n")}
Allow: /
${disallow}

${BLOCKED_AGENTS.map((agent) => `User-agent: ${agent}`).join("\n")}
Disallow: /

Sitemap: ${SITE_ORIGIN}/sitemap.xml
`;
}
