import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";

import "./globals.css";
import DataContextProvider from "@/contexts/useAllContext";
import { ThemeProvider } from "@/contexts/ThemeContext";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata = {
  title: {
    default:
      "Mahbub Alam | Full Stack Developer Portfolio - React, Node.js, Next.js, React Native, PHP Expert",
    template: "%s | Mahbub Alam Portfolio",
  },
  description:
    "Mahbub Alam is a Full Stack Developer specializing in React, Node.js, PHP, and modern web technologies. Based in Dhaka, Bangladesh. Contact: admin@mahbub.dev, mahbub@lunetsoft.com, mahbubcse96@gmail.com",
  keywords: [
    "Mahbub Alam",
    "Mahbub",
    "Full Stack Developer",
    "Web Developer",
    "React Developer",
    "PHP Developer",
    "Node.js Developer",
    "Next.js Developer",
    "React Native Developer",
    "Bangladesh Developer",
    "Dhaka Developer",
    "admin@mahbub.dev",
    "mahbub@lunetsoft.com",
    "mahbubcse96@gmail.com",
    "mahbub.alam.sobuz@gmail.com",
    "Brotecs Technologies",
    "VoIP Solutions",
    "Laravel Developer",
    "CodeIgniter Developer",
    "MongoDB Developer",
    "MySQL Developer",
    "AWS Developer",
    "Docker Developer",
    "DevSecOps Engineer",
    "System Architect",
    "Cloud Computing Expert",
    "Web Application Development",
    "Mobile App Development",
    "API Development",
    "Microservices Architecture",
    "Agile Development",
    "Test Driven Development",
    "Continuous Integration",
    "Software Engineering",
    "Computer Science",
    "Stamford University Bangladesh",
    "Freelance Developer",
    "Remote Developer",
    "Bangladesh IT Services",
    "Dhaka IT Solutions",
    "Web Design",
    "UI/UX Development",
    "Frontend Development",
    "Backend Development",
    "Database Design",
    "Server Administration",
    "Linux Administration",
    "Git Version Control",
    "CI/CD Pipeline",
    "DevOps Engineer",
    "Software Consultant",
    "Technical Lead",
    "Project Manager",
    "Team Lead",
    "Code Review",
    "Performance Optimization",
    "Security Implementation",
    "Scalable Architecture",
    "Enterprise Solutions",
    "Startup Development",
    "E-commerce Development",
    "CMS Development",
    "WordPress Development",
    "Shopify Development",
    "Custom Software Development",
    "Legacy System Migration",
    "Database Migration",
    "API Integration",
    "Third-party Integration",
    "Payment Gateway Integration",
    "Social Media Integration",
    "Analytics Integration",
    "SEO Optimization",
    "Performance Testing",
    "Load Testing",
    "Security Testing",
    "Unit Testing",
    "Integration Testing",
    "End-to-End Testing",
    "Bug Fixing",
    "Code Refactoring",
    "Technical Documentation",
    "User Manuals",
    "API Documentation",
    "System Architecture Documentation",
    "Database Schema Design",
    "Data Modeling",
    "Business Logic Implementation",
    "User Authentication",
    "Authorization Systems",
    "Role-based Access Control",
    "Multi-factor Authentication",
    "OAuth Implementation",
    "JWT Tokens",
    "Session Management",
    "Cookie Management",
    "Data Validation",
    "Input Sanitization",
    "SQL Injection Prevention",
    "XSS Prevention",
    "CSRF Protection",
    "HTTPS Implementation",
    "SSL Certificates",
    "Domain Management",
    "Hosting Management",
    "Server Monitoring",
    "Log Management",
    "Error Tracking",
    "Performance Monitoring",
    "Uptime Monitoring",
    "Backup Management",
    "Disaster Recovery",
    "Data Backup",
    "Version Control",
    "Code Deployment",
    "Environment Management",
    "Development Environment",
    "Staging Environment",
    "Production Environment",
    "Configuration Management",
    "Environment Variables",
    "Secrets Management",
    "API Keys Management",
    "Database Credentials",
    "Server Credentials",
    "SSL Certificates Management",
    "Domain SSL",
    "Wildcard SSL",
    "Multi-domain SSL",
    "Email Configuration",
    "SMTP Setup",
    "IMAP Setup",
    "POP3 Setup",
    "Email Templates",
    "Email Automation",
    "Email Marketing",
    "Newsletter Management",
    "Contact Form",
    "Feedback System",
    "Support Ticket System",
    "Live Chat Integration",
    "Customer Support",
    "Technical Support",
    "Bug Reporting",
    "Feature Request",
    "User Feedback",
    "Analytics Dashboard",
    "Google Analytics",
    "Google Search Console",
    "Bing Webmaster Tools",
    "Yandex Webmaster",
    "SEO Tools",
    "Keyword Research",
    "On-page SEO",
    "Off-page SEO",
    "Technical SEO",
    "Local SEO",
    "Mobile SEO",
    "Page Speed Optimization",
    "Core Web Vitals",
    "Lighthouse Score",
    "GTmetrix Score",
    "PageSpeed Insights",
    "WebPageTest",
    "Performance Budget",
    "Critical CSS",
    "CSS Minification",
    "JavaScript Minification",
    "Image Optimization",
    "WebP Images",
    "Responsive Images",
    "Lazy Loading",
    "Preloading",
    "Prefetching",
    "Service Workers",
    "Progressive Web App",
    "Offline Support",
    "Push Notifications",
    "App-like Experience",
    "Mobile-first Design",
    "Responsive Design",
    "Cross-browser Compatibility",
    "Accessibility",
    "WCAG Guidelines",
    "ARIA Labels",
    "Screen Reader Support",
    "Keyboard Navigation",
    "Color Contrast",
    "Font Size",
    "Readability",
    "User Experience",
    "User Interface",
    "Design Systems",
    "Component Libraries",
    "Design Tokens",
    "CSS Variables",
    "CSS Grid",
    "CSS Flexbox",
    "CSS Animations",
    "CSS Transitions",
    "CSS Transforms",
    "CSS Filters",
    "CSS Custom Properties",
    "CSS Modules",
    "Styled Components",
    "Emotion",
    "Tailwind CSS",
    "Bootstrap",
    "Material-UI",
    "Ant Design",
    "Chakra UI",
    "Semantic UI",
    "Foundation",
    "Bulma",
    "Pure CSS",
    "Skeleton",
    "Milligram",
    "Spectre.css",
    "UIkit",
    "Element UI",
    "Vuetify",
    "Quasar",
    "Nuxt.js",
    "Gatsby",
    "Next.js",
    "Create React App",
    "Vite",
    "Webpack",
    "Rollup",
    "Parcel",
    "ESBuild",
    "SWC",
    "Babel",
    "TypeScript",
    "Flow",
    "ESLint",
    "Prettier",
    "Husky",
    "Lint-staged",
    "Commitizen",
    "Conventional Commits",
    "Semantic Release",
    "Changelog Generation",
    "Release Notes",
    "Version Management",
    "Semantic Versioning",
    "Git Tags",
    "Git Branches",
    "Git Flow",
    "GitHub Flow",
    "GitLab Flow",
    "Feature Branches",
    "Hotfix Branches",
    "Release Branches",
    "Main Branch",
    "Develop Branch",
    "Pull Requests",
    "Code Review",
    "Merge Conflicts",
    "Rebasing",
    "Squashing",
    "Cherry-picking",
    "Git Hooks",
    "Pre-commit Hooks",
    "Post-commit Hooks",
    "Pre-push Hooks",
    "Post-merge Hooks",
    "Git Aliases",
    "Git Config",
    "Git Ignore",
    "Git Attributes",
    "Git Submodules",
    "Git Worktrees",
    "Git LFS",
    "Git Bisect",
    "Git Blame",
    "Git Log",
    "Git Show",
    "Git Diff",
    "Git Status",
    "Git Add",
    "Git Commit",
    "Git Push",
    "Git Pull",
    "Git Fetch",
    "Git Clone",
    "Git Init",
    "Git Remote",
    "Git Branch",
    "Git Checkout",
    "Git Merge",
    "Git Rebase",
    "Git Reset",
    "Git Revert",
    "Git Cherry-pick",
    "Git Stash",
    "Git Clean",
    "Git Archive",
    "Git Bundle",
    "Git Notes",
    "Git Replace",
    "Git Filter-branch",
    "Git Subtree",
    "Git Worktree",
    "Git LFS",
    "Git Credential",
    "Git Config",
    "Git Help",
    "Git Documentation",
    "Git Tutorials",
    "Git Best Practices",
    "Git Workflows",
    "Git Strategies",
    "Git Tools",
    "Git GUI",
    "Git CLI",
    "Git IDE Integration",
    "VS Code Git",
    "IntelliJ Git",
    "Eclipse Git",
    "Atom Git",
    "Sublime Text Git",
    "Vim Git",
    "Emacs Git",
    "GitHub Desktop",
    "GitKraken",
    "SourceTree",
    "SmartGit",
    "TortoiseGit",
    "Git Extensions",
    "Git Cola",
    "Gitg",
    "Giggle",
    "QGit",
    "GitNub",
    "GitBox",
    "GitUp",
    "Fork",
    "GitAhead",
    "GitKraken",
    "SourceTree",
    "SmartGit",
    "TortoiseGit",
    "Git Extensions",
    "Git Cola",
    "Gitg",
    "Giggle",
    "QGit",
    "GitNub",
    "GitBox",
    "GitUp",
    "Fork",
    "GitAhead",
  ],
  authors: [{ name: "Mahbub Alam" }],
  creator: "Mahbub Alam",
  publisher: "Mahbub Alam",
  metadataBase: new URL("https://mahbub.dev"),
  alternates: {
    canonical: "https://mahbub.dev/",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  verification: {
    google: "your-google-verification-code-here", // Replace with actual Google Search Console verification code
    yandex: "your-yandex-verification-code-here", // Optional: Yandex verification
    bing: "your-bing-verification-code-here", // Optional: Bing verification
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://mahbub.dev",
    title:
      "Mahbub Alam | Full Stack Developer Portfolio - React, Node.js, Next.js, React Native, PHP Expert",
    description:
      "Mahbub Alam is a Full Stack Developer specializing in React, Node.js, PHP, and modern web technologies. Based in Dhaka, Bangladesh. Contact: admin@mahbub.dev, mahbub@lunetsoft.com, mahbubcse96@gmail.com",
    siteName: "Mahbub Alam Portfolio",
    images: [
      {
        url: "https://mahbub.dev/assets/img/profile.png",
        width: 1200,
        height: 630,
        alt: "Mahbub Alam - Full Stack Developer Portfolio",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title:
      "Mahbub Alam | Full Stack Developer Portfolio - React, Node.js, Next.js, React Native, PHP Expert",
    description:
      "Mahbub Alam is a Full Stack Developer specializing in React, Node.js, PHP, and modern web technologies. Based in Dhaka, Bangladesh. Contact: admin@mahbub.dev, mahbub@lunetsoft.com, mahbubcse96@gmail.com",
    images: ["https://mahbub.dev/assets/img/profile.png"],
    creator: "@mahbubcse96",
    site: "@mahbubcse96",
  },
  other: {
    "google-site-verification": "your-google-verification-code-here",
    "msvalidate.01": "your-bing-verification-code-here",
    "yandex-verification": "your-yandex-verification-code-here",
    "theme-color": "#0a192f",
    "msapplication-TileColor": "#0a192f",
    "apple-mobile-web-app-capable": "yes",
    "apple-mobile-web-app-status-bar-style": "default",
    "apple-mobile-web-app-title": "Mahbub Portfolio",
    "application-name": "Mahbub Portfolio",
    "mobile-web-app-capable": "yes",
    "format-detection": "telephone=no",
    "format-detection": "email=no",
    "format-detection": "address=no",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.variable}>
      <head>
        <link rel="icon" href="https://mahbub.dev/favicon.ico" />
        <link rel="apple-touch-icon" href="https://mahbub.dev/logo192.png" />
        <link rel="manifest" href="https://mahbub.dev/manifest.json" />
        <meta name="theme-color" content="#0a192f" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="format-detection" content="telephone=no" />

        {/* Preconnect for performance */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />

        {/* Enhanced Structured Data */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Person",
              "@id": "https://mahbub.dev",
              name: "Mahbub Alam",
              givenName: "Mahbub",
              familyName: "Alam",
              alternateName: ["Mahbub", "Mahbub Alam", "Md Mahbub Alam"],
              url: "https://mahbub.dev",
              image: "https://mahbub.dev/assets/img/profile.png",
              jobTitle: "Full Stack Developer",
              description:
                "Full Stack Developer specializing in React, Node.js, PHP, and modern web technologies",
              email: [
                "admin@mahbub.dev",
                "support@mahbub.dev",
                "mahbub@lunetsoft.com",
              ],
              telephone: "+880-1XXX-XXXXXX",
              worksFor: {
                "@type": "Organization",
                name: "Brotecs Technologies Ltd",
                url: "https://brotecs.com",
                address: {
                  "@type": "PostalAddress",
                  addressLocality: "Dhaka",
                  addressCountry: "Bangladesh",
                },
              },
              alumniOf: {
                "@type": "CollegeOrUniversity",
                name: "Stamford University Bangladesh",
                url: "https://stamforduniversity.edu.bd",
              },
              address: {
                "@type": "PostalAddress",
                addressLocality: "Dhaka - 1230",
                addressCountry: "Bangladesh",
                addressRegion: "Dhaka",
              },
              knowsAbout: [
                "Full Stack Development",
                "React.js",
                "Node.js",
                "PHP",
                "Laravel",
                "CodeIgniter",
                "MongoDB",
                "MySQL",
                "Cloud Computing",
                "VoIP Solutions",
                "System Architecture",
                "DevSecOps",
                "Docker",
                "AWS",
              ],
              hasOccupation: {
                "@type": "Occupation",
                name: "Full Stack Developer",
                skills: [
                  "React",
                  "Node.js",
                  "PHP",
                  "Laravel",
                  "AWS",
                  "Docker",
                  "MongoDB",
                  "MySQL",
                ],
                occupationalCategory:
                  "15-1250 Software Developers and Programmers",
              },
              sameAs: [
                "https://github.com/mahbub96",
                "https://linkedin.com/in/md-mahbub-alam-6b751821b",
                "https://fb.me/MahbubCSE96",
              ],
            }),
          }}
        />

        {/* Local Business Schema */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "LocalBusiness",
              "@id": "https://mahbub.dev#business",
              name: "Mahbub Alam - Full Stack Developer",
              description:
                "Full Stack Developer specializing in React, Node.js, PHP, and modern web technologies",
              url: "https://mahbub.dev",
              telephone: "+880-1XXX-XXXXXX",
              email: [
                "admin@mahbub.dev",
                "support@mahbub.dev",
                "mahbub@lunetsoft.com",
              ],
              address: {
                "@type": "PostalAddress",
                addressLocality: "Dhaka",
                addressCountry: "Bangladesh",
                addressRegion: "Dhaka",
              },
              geo: {
                "@type": "GeoCoordinates",
                latitude: 23.8103,
                longitude: 90.4125,
              },
              areaServed: {
                "@type": "Country",
                name: "Bangladesh",
              },
              serviceArea: {
                "@type": "Country",
                name: "Worldwide",
              },
              hasOfferCatalog: {
                "@type": "OfferCatalog",
                name: "Web Development Services",
                itemListElement: [
                  {
                    "@type": "Offer",
                    itemOffered: {
                      "@type": "Service",
                      name: "Full Stack Web Development",
                      description: "React, Node.js, PHP development services",
                    },
                  },
                  {
                    "@type": "Offer",
                    itemOffered: {
                      "@type": "Service",
                      name: "VoIP Solutions",
                      description: "Voice over IP system development",
                    },
                  },
                ],
              },
            }),
          }}
        />

        {/* FAQ Schema */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "FAQPage",
              mainEntity: [
                {
                  "@type": "Question",
                  name: "Who is Mahbub Alam?",
                  acceptedAnswer: {
                    "@type": "Answer",
                    text: "Mahbub Alam is a Full Stack Developer based in Dhaka, Bangladesh, specializing in React, Node.js, PHP, and modern web technologies. He works at Brotecs Technologies Ltd and has expertise in VoIP solutions and system architecture.",
                  },
                },
                {
                  "@type": "Question",
                  name: "What technologies does Mahbub Alam work with?",
                  acceptedAnswer: {
                    "@type": "Answer",
                    text: "Mahbub Alam works with React.js, Node.js, PHP, Laravel, CodeIgniter, MongoDB, MySQL, AWS, Docker, and various other modern web technologies for full stack development.",
                  },
                },
                {
                  "@type": "Question",
                  name: "How can I contact Mahbub Alam?",
                  acceptedAnswer: {
                    "@type": "Answer",
                    text: "You can contact Mahbub Alam via email at admin@mahbub.dev, support@mahbub.dev, or mahbub@lunetsoft.com. He is based in Dhaka, Bangladesh and available for freelance projects and full-time opportunities.",
                  },
                },
              ],
            }),
          }}
        />
      </head>
      <body className={inter.className} suppressHydrationWarning={true}>
        <DataContextProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </DataContextProvider>
      </body>
    </html>
  );
}
