name: Build and Deploy to VPS

on:
  push:
    branches:
      - deploy

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Archive build files
        run: tar -czf build.tar.gz .next package.json next.config.js public

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-build
          path: build.tar.gz

  deploy:
    name: Deploy to VPS
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: site-build

      - name: Copy build files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_SSH_VPS }}
          source: "build.tar.gz"
          target: "/var/www/html/mahbub.dev"

      - name: SSH into VPS and Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_SSH_VPS }}
          docker: false
          script: |
            cd /var/www/html/mahbub.dev

            # Extract new build
            tar -xzf build.tar.gz
            rm build.tar.gz

            # Install production dependencies
            npm install --production

            # Drop the database (replace 'mydb' with your DB name)
            mongo mydb --eval "db.dropDatabase()"

            # Seed the database
            npm run seed

            # Start or restart Next.js app with PM2
            pm2 restart next-app || pm2 start npm --name "next-app" -- run start
            pm2 save
