name: Build and Deploy to VPS

on:
  push:
    branches:
      - deploy

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Next.js app
        run: yarn build

      - name: Archive build output + essential files
        run: |
          tar -czf build.tar.gz \
            .next \
            public \
            package.json \
            yarn.lock \
            next.config.js

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-build
          path: build.tar.gz

  deploy:
    name: Deploy to VPS
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: site-build

      - name: Copy build files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_SSH_VPS }}
          source: "build.tar.gz"
          target: "/var/www/html/mahbub.dev"

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v1.2.0
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          RUN_SEED: ${{ secrets.RUN_SEED }}
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_SSH_VPS }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

            nvm use 18 || true
            PM2_BIN=$(which pm2)
            echo "PM2 found at: $PM2_BIN"

            cd /var/www/html/mahbub.dev || exit 1

            # Remove old files except .env and logs
            find . -mindepth 1 ! -name ".env" ! -name "logs" -exec rm -rf {} +

            # Extract uploaded build
            tar -xzf build.tar.gz
            rm build.tar.gz

            # Optional seed script
            if [ "$RUN_SEED" = "true" ]; then
              echo "Running seed script"
              yarn seed || echo "Seed script failed"
            else
              echo "Skipping seed"
            fi

            # Start or restart app with PM2
            if $PM2_BIN describe next-app > /dev/null 2>&1; then
              echo "Restarting existing PM2 process..."
              $PM2_BIN restart next-app
            else
              echo "Starting new PM2 process..."
              $PM2_BIN start npm --name "next-app" -- start
            fi

            $PM2_BIN save

            # Restart nginx
            sudo systemctl restart nginx
            sudo systemctl enable nginx
