name: Build and Deploy to VPS

on:
  push:
    branches:
      - deploy

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Archive full project
        run: tar -czf build.tar.gz package.json package-lock.json next.config.js public src

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-build
          path: build.tar.gz

  deploy:
    name: Deploy to VPS
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: site-build

      - name: Copy build files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_SSH_VPS }}
          source: "build.tar.gz"
          target: "/var/www/html/mahbub.dev"

      - name: SSH into VPS and Deploy
        uses: appleboy/ssh-action@v1.2.0
        env:
          RUN_SEED: ${{ secrets.RUN_SEED }}
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_SSH_VPS }}
          script: |
            # Absolute paths for Node & npm
            NODE_BIN="/home/ubuntu/.nvm/versions/node/v18.20.8/bin"
            export PATH="$NODE_BIN:$PATH"

            PM2_BIN="/home/ubuntu/.nvm/versions/node/v18.20.8/bin/pm2"

            cd /var/www/html/mahbub.dev || exit 1

            # Extract uploaded source
            if [ ! -f build.tar.gz ]; then
              echo "build.tar.gz not found"
              ls -la
              exit 1
            fi
            tar -xzf build.tar.gz
            rm build.tar.gz

            # Install production dependencies
            npm ci --production

            # Optional seed script
            if [ "$RUN_SEED" = "true" ]; then
              echo "Running seed script"
              npm run seed || echo "Seed script failed"
            else
              echo "Skipping seed"
            fi

            # Start or restart app using PM2
            $PM2_BIN restart next-app || $PM2_BIN start npm --name "next-app" -- start
            $PM2_BIN save

            # Restart nginx
            sudo systemctl restart nginx
            sudo systemctl status nginx --no-pager
            sudo systemctl enable nginx
