name: Build and Deploy to VPS

on:
  push:
    branches:
      - deploy

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies (prod only)
        run: npm ci --omit=dev

      - name: Build Next.js app
        run: npm run build

      - name: Archive build output + source
        run: |
          tar -czf build.tar.gz \
            .next \
            package.json package-lock.json \
            public \
            scripts \
            src \
            tsconfig.json \
            next.config.js \
            node_modules

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-build
          path: build.tar.gz

  deploy:
    name: Deploy to VPS
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: site-build

      - name: Copy build files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_SSH_VPS }}
          source: "build.tar.gz"
          target: "/var/www/html/mahbub.dev"

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v1.2.0
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          RUN_SEED: ${{ secrets.RUN_SEED }}
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_SSH_VPS }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

            nvm use 22 || nvm install 22
            PM2_BIN=$(which pm2)
            echo "PM2 found at: $PM2_BIN"

            cd /var/www/html/mahbub.dev || exit 1

            # Clean old files except .env and logs
            find . -mindepth 1 ! -name ".env" ! -name "logs" -exec rm -rf {} +

            # Extract build safely
            tar -xzf build.tar.gz
            rm build.tar.gz

            # Optional seed
            if [ "$RUN_SEED" = "true" ]; then
              echo "Running seed script"
              npm run seed || echo "Seed failed"
            else
              echo "Skipping seed"
            fi

            # Start/restart PM2 app safely
            if $PM2_BIN list | grep -q "next-app"; then
              echo "Restarting existing PM2 process..."
              $PM2_BIN restart next-app --update-env
            else
              echo "Starting new PM2 process..."
              $PM2_BIN start npm --name "next-app" -- start
            fi

            $PM2_BIN save

            # Restart nginx
            sudo systemctl restart nginx
            sudo systemctl enable nginx
