name: Build and Deploy to Test Server

on:
  push:
    branches:
      - deploy # Trigger when pushing to 'deploy' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Install dependencies
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      # 4️⃣ Build Next.js app
      - name: Build Next.js App
        run: yarn build

      # 5️⃣ Prepare deployment folder
      - name: Prepare Deployment Package
        run: |
          mkdir -p deploy
          cp -r .next public src ecosystem.config.js package.json yarn.lock deploy/
          cp env.prod deploy/.env.local || true
          echo "✅ Files copied to deploy directory"
          ls -la deploy

      # 6️⃣ Ensure remote folder exists and correct permissions
      - name: Ensure Remote Directory
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_SSH_VPS }}
          script: |
            sudo mkdir -p /var/www/html/test.mahbub.dev
            sudo chown -R ${{ secrets.USER }}:${{ secrets.USER }} /var/www/html/test.mahbub.dev
            sudo rm -rf /var/www/html/test.mahbub.dev/*  # Optional cleanup

      # 7️⃣ Upload files to VPS
      - name: Deploy to VPS (Test)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_SSH_VPS }}
          source: "./deploy/*"
          target: "/var/www/html/test.mahbub.dev"
          strip_components: 1

      # 8️⃣ Install dependencies & restart PM2
      - name: Install dependencies and restart PM2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_SSH_VPS }}
          script: |
            cd /var/www/html/test.mahbub.dev
            yarn install --production --frozen-lockfile
            pm2 restart test.mahbub.dev || pm2 start ecosystem.config.js --only test.mahbub.dev
            pm2 save
