name: Build and Deploy Test Server

on:
  push:
    branches:
      - cicd

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ✅ Step 1: Checkout source code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ✅ Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"

      # ✅ Step 3: Install dependencies
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      # ✅ Step 4: Create environment file
      - name: Create Environment File
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env

      # ✅ Step 5: Build Next.js app
      - name: Build Next.js App
        run: yarn build

      # ✅ Step 6: Prepare deployment package (including scripts)
      - name: Prepare Deployment Package
        run: |
          mkdir deploy
          cp -r .next public scripts ecosystem.config.js package.json yarn.lock deploy/
          cp .env deploy/.env || true

      # ✅ Step 7: Deploy built files to VPS
      - name: Deploy to VPS (Test)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_SSH_VPS }}
          source: "deploy/*"
          target: "/var/www/html/test.mahbub.dev"

      # ✅ Step 8: Install dependencies, run seeder & restart app
      - name: Run Seeder & Restart Test App on Port 4000
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_SSH_VPS }}
          script: |
            cd /var/www/html/test.mahbub.dev

            # Load Node
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 22
            export PATH="$NVM_DIR/versions/node/v22.14.0/bin:$PATH"

            # Check versions
            node -v
            yarn -v
            pm2 -v || npm install -g pm2

            # Install dependencies
            yarn install --frozen-lockfile --production=false

            # Run database seeder (if exists)
            if [ -f scripts/seedProjects.js ]; then
              echo "🚀 Running Seeder..."
              node scripts/seedProjects.js
            else
              echo "⚠️ Seeder file not found, skipping..."
            fi

            # Restart or start PM2 app
            export PORT=4000
            pm2 delete test.mahbub.dev || true
            pm2 start npm --name "test.mahbub.dev" -- start --update-env
            pm2 save
