name: Build and Deploy Test Server

on:
  push:
    branches:
      - cicd

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ✅ Step 1: Checkout source code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ✅ Step 2: Setup Node.js (match your server Node version)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"

      # ✅ Step 3: Install dependencies
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      # ✅ Step 4: Build Next.js app
      - name: Build Next.js App
        run: yarn build

      # ✅ Step 5: Prepare deployment package
      - name: Prepare Deployment Package
        run: |
          mkdir deploy
          cp -r .next public ecosystem.config.js package.json yarn.lock deploy/
          cp .env deploy/.env || true

      # ✅ Step 6: Deploy built files to your VPS
      - name: Deploy to VPS (Test)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_SSH_VPS }}
          source: "deploy/*"
          target: "/var/www/html/test.mahbub.dev"

      # ✅ Step 7: Install dependencies, run seeder & restart app via PM2 on port 4000
      - name: Run Seeder & Restart Test App on Port 4000
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_SSH_VPS }}
          script: |
            cd /var/www/html/test.mahbub.dev

            # Load NVM & use correct Node version
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 22
            nvm use 22

            # Install dependencies
            yarn install --frozen-lockfile --production=false

            # Run database seeder if defined
            yarn seed || echo "No seed script found, skipping..."

            # Set PORT environment variable for PM2
            export PORT=4000

            # Restart or start PM2 process on port 4000
            pm2 delete test.mahbub.dev || true
            pm2 start npm --name "test.mahbub.dev" -- start
            pm2 save
